' Общие параметры ЧБ для диаграмм диплома (вставка: !include _skin_bw.puml)
skinparam backgroundColor white
skinparam shadowing false
skinparam roundcorner 0
skinparam linetype ortho
skinparam arrowColor black
skinparam arrowFontColor black
skinparam defaultFontColor black
skinparam titleFontColor black
skinparam titleBorderColor black
skinparam rectangleBorderColor black
skinparam rectangleBackgroundColor white
skinparam packageBorderColor black
skinparam packageBackgroundColor white
skinparam packageFontColor black
skinparam nodeBorderColor black
skinparam nodeBackgroundColor white
skinparam nodeFontColor black
skinparam componentBorderColor black
skinparam componentBackgroundColor white
skinparam componentFontColor black
skinparam databaseBorderColor black
skinparam databaseBackgroundColor white
skinparam databaseFontColor black
skinparam queueBorderColor black
skinparam queueBackgroundColor white
skinparam queueFontColor black
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam actorFontColor black
skinparam participantBorderColor black
skinparam participantBackgroundColor white
skinparam participantFontColor black
skinparam sequenceArrowColor black
skinparam sequenceLifeLineBorderColor black
skinparam entityBorderColor black
skinparam entityBackgroundColor white
skinparam entityFontColor black
skinparam entityHeaderBackgroundColor white
skinparam entityHeaderFontColor black
